# Generated by Django 3.1.3 on 2020-11-13 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Aliment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nutriscore', models.CharField(max_length=1)),
                ('image_url', models.URLField()),
                ('product_url', models.URLField()),
                ('sugar', models.CharField(max_length=10)),
                ('fat', models.CharField(max_length=10)),
                ('sel', models.CharField(max_length=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='my_aliments',
            field=models.ManyToManyField(to='store.Aliment'),
        ),
    ]
