# Generated by Django 3.1.3 on 2020-11-20 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20201115_1708'),
    ]

    operations = [
        migrations.DeleteModel(
            name='My_aliments',
        ),
        migrations.AlterField(
            model_name='aliment',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliments', to='store.category'),
        ),
        migrations.AlterField(
            model_name='aliment',
            name='energy',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='aliment',
            name='fat',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='aliment',
            name='salt',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='aliment',
            name='sugar',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='my_aliments',
            field=models.ManyToManyField(to='store.Aliment'),
        ),
    ]
