# Generated by Django 3.1.3 on 2020-11-20 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20201120_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliment',
            name='energy',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aliment',
            name='fat',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aliment',
            name='salt',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aliment',
            name='sugar',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
