# Generated by Django 3.1.3 on 2020-11-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20201120_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliment',
            name='energy',
            field=models.CharField(default=None, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='aliment',
            name='fat',
            field=models.CharField(default=None, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='aliment',
            name='image_url',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='aliment',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='aliment',
            name='nutriscore',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='aliment',
            name='product_url',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='aliment',
            name='salt',
            field=models.CharField(default=None, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='aliment',
            name='sugar',
            field=models.CharField(default=None, max_length=100, null=True, unique=True),
        ),
    ]
