# Generated by Django 3.1.4 on 2020-12-04 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20201202_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='aliment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.aliment', unique=True),
        ),
    ]
