# Generated by Django 3.1.2 on 2021-03-06 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_auto_20210306_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliment',
            name='notation',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
