# Generated by Django 3.1.2 on 2021-03-06 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_aliment_average'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliment',
            name='average',
            field=models.FloatField(default=0, null=True),
        ),
    ]
