language: python
python:
  - "3.8"
# command to install dependencies
install:
  - pip install -r requirements.txt
  
env:
  global:
  - DJANGO_SETTINGS_MODULE="pur_beurre_project.travis"

services:
  - postgresql
# command to run tests
script:
  - python manage.py test