language: python
python:
  - "3.8"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - export ENVIRONEMENT=PRODUCTION
  - export SECRET_KEY=$SECRET_KEY
  - python manage.py test

env: DJANGO_SETTINGS_MODULE="pur_beurre_project.travis"

services:
  - postgresql