# Generated by Django 3.1.3 on 2020-11-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20201113_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='aliment',
            name='energy',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='aliment',
            name='fat',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='aliment',
            name='sel',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='aliment',
            name='sugar',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
